server:
  port: 7009
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/outongjiang/springcouldConfig.git

  application:
    name: springcloud-config-server
myname: 1

