server:
  port: 7008
spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7004/eureka/,http://localhost:7005/eureka/
  instance:
    instance-id: springcloud-zuul-7008
    prefer-ip-address: true
info:
  app.name: person.otj
  company.name: outongjiang
  verson.name: 1.0
zuul:
  routes:
    pro.serviceId: springcould-provider
    pro.path: /pro/**
  ignored-services: "*"